Feature/ot221 51
alkemyTech/OT221-client pull request #25
Opened 2022-06-29 17:30 UTC by rodrigo1995vav

## Issue ticket link
https://alkemy-labs.atlassian.net/browse/OT221-51

## Summary
-Now everything comes from the server, the database handles the sorting and searching methods
-A user can be searched by email

## Evidence

**Table showing up users with sorting, searching, and pagination functionalities**
![2022-07-14 00_33_21-SOMOS MAS](https://user-images.githubusercontent.com/79865376/178895769-7dc81003-5383-4a9b-955c-ada0117badba.png)

**Delete User Confirmation**
![2022-07-14 00_33_29-SOMOS MAS](https://user-images.githubusercontent.com/79865376/178895878-d17d3b52-8f75-435a-bfee-81fe9e245452.png)

![2022-07-14 00_33_35-SOMOS MAS](https://user-images.githubusercontent.com/79865376/178895974-f32cac7b-c13c-49e8-8cdd-63632064b996.png)

-Add Users table allowing admin to configure users data.
![2022-07-14 00_51_40-SOMOS MAS](https://user-images.githubusercontent.com/79865376/178896041-aa6066c1-9c52-414d-be9e-427699ae6aa3.png)

-If there's no data to show 
![2022-07-14 00_51_52-SOMOS MAS](https://user-images.githubusercontent.com/79865376/178896160-c8d814d9-2ce5-4a6a-a2cd-78899adb7e3e.png)

2022-07-01 00:56 UTC, GauntStrelok reviewed
Arregla esos errores que tenes de mergeo

2022-07-01 00:56 UTC, GauntStrelok commented on package.json
> +<<<<<<< HEAD
Mal mergeado este archivo, abrirlo en el IDE para arreglarlo

2022-07-01 00:56 UTC, GauntStrelok commented on src/App.js
> +<<<<<<< HEAD
Mal mergeaqdo este archivo tambien

2022-07-03 19:19 UTC, GauntStrelok requested changes
Juntemonos y veamoslo juntos

2022-07-03 19:19 UTC, GauntStrelok commented on package.json
> +<<<<<<< HEAD
Sigue mal mergeado

2022-07-05 03:23 UTC, GauntStrelok commented on src/components/usersConfigTable/UsersConfigTable.jsx
> +import "bootstrap/dist/css/bootstrap.min.css";
Estaria bueno que tenga otro nombre esta pantalla, que te diga mas acerca de que se trata, que es un listado de usuarios simplemente estaria bien, o un listado admin de usuarios tambien, y no tanto este nombre que no entiendo bien del todo que significa a menos que conozca el proyecto

2022-07-05 03:24 UTC, GauntStrelok commented on src/components/usersConfigTable/EditableRow.js
> +    <tr key={editFormData.id}>
La edicion online, parece copada, pero a NADIE le gusta jaja, todos prefieren que se abra el formulario al editar un elemento, y luego al guardar el formulario que se recargue la lista(o, mejor aun y mas performante, que se recargue simplemente el elemento que modificamos)

2022-07-05 03:25 UTC, GauntStrelok commented on src/components/usersConfigTable/ModalConfirmDelete.jsx
> +import React from 'react'
Tenes sweetalert2 como dependencia en el proyecto, es al pedo que crees un nuevo modal confirm delete, cuando podrias usar facilmente uno de sweetalert2

2022-07-05 03:26 UTC, GauntStrelok commented on src/components/usersConfigTable/ModalSaveChanges.jsx
> +import React from "react";
Lo mismo que en el ModalConfirmDelete

2022-07-05 03:27 UTC, GauntStrelok commented on src/components/usersConfigTable/UsersConfigTable.jsx
> +        {editContactId === user.id ? (
Estaria mas bueno sacar la row afuera como un componente separado que maneje el estado de edicion y readonly dentro de su propio componente para evitar tener que recargar toda la lista cada vez que cambias el estado de edicion de una row en especifico

2022-07-05 03:28 UTC, GauntStrelok commented on src/components/usersConfigTable/UsersConfigTable.jsx
> +  const filter = (e) => {
Trata de no crear funciones con nombres genericos como filter, ponele si queres por ejemplo filterEmailBySearch o algo asi que diga que hace este filter, o usalo directamente si consideras que no tiene sentido crearlo como funcion.
Tambien trata de no usar nombres que son metodos de otras funciones, ya que pueden llegar a confundir.

2022-07-05 03:29 UTC, GauntStrelok commented on src/components/usersConfigTable/UsersConfigTable.jsx
> +  const filter = (e) => {
Capaz filterData podes usar, o searchData tambien

2022-07-05 03:33 UTC, GauntStrelok commented on src/components/usersConfigTable/UsersConfigTable.jsx
> +    if (order === "asc" && col !== "id") {
junta los ifs, por ejemplo pregunta primero si la columna es id

2022-07-05 03:33 UTC, GauntStrelok commented on src/components/usersConfigTable/UsersConfigTable.jsx
> +        a[col].toLowerCase() < b[col].toLowerCase() ? 1 : -1
Que pasa si tenes otra columna que no es id de tipo numerico? como lo solucionarias aca?

2022-07-05 03:35 UTC, GauntStrelok commented on src/components/usersConfigTable/UsersConfigTable.jsx
> +                        {order === "dsc" ? (
Me parece que te falta aca preguntar tambien por la columna que se esta ordenando

2022-07-05 03:35 UTC, GauntStrelok commented
La pregunta mia final es, lo mergeamos como esta o queres hacerle mas cambios?

2022-07-05 14:31 UTC, rodrigo1995vav commented on src/components/usersConfigTable/UsersConfigTable.jsx
> +                        {order === "dsc" ? (
Me re sirve todo el feedback, prefiero hacerle cambios y mejorar antes de mergear

2022-07-14 13:01 UTC, GauntStrelok commented on src/components/UsersList/UsersList.jsx
> +  const [editContactId, setEditContactId] = useState(null);
Realmente no necesitas este valor si ya tenes el id en editFormData

2022-07-14 13:05 UTC, merged