create navbar responsive wich image logo in react for the moment
alkemyTech/OT221-client pull request #4
Opened 2022-06-17 19:40 UTC by MarcosSWeis

https://alkemy-labs.atlassian.net/browse/OT221-21
![image](https://user-images.githubusercontent.com/91438906/174390494-f4d0f6cc-9465-4908-a68a-909587b8b81c.png)

Image of the logo hardcoded in react so that it can be seen, since redux is not configured to make the request on the server

2022-06-22 04:21 UTC, GauntStrelok requested changes
Hacer ademas del arreglo, un pull de main para arreglar conflictos, y, cuando hagas el pull elimina los archivos de package-lock.json y yarn.lock

2022-06-22 04:21 UTC, GauntStrelok commented on src/components/Navbar.jsx
> +              <ul class="navbar-nav me-auto mb-2 mb-lg-0 mx-auto">
Segun el ticket, el menu tiene que ser un array de elementos

2022-06-24 04:30 UTC, merged

2022-06-24 04:30 UTC, MarcosSWeis commented
![image](https://user-images.githubusercontent.com/91438906/175462178-e02a0dfd-d80f-4595-abea-fd551d313b6d.png)
el manu ya es un array 
![image](https://user-images.githubusercontent.com/91438906/175462371-c3458376-d52f-435b-8a2a-4940e44abbca.png)
la vista sigue igual 
y los conflictos están resueltos

2022-06-24 11:00 UTC, GauntStrelok commented
Ojo, mergeaste este PR a main, eso lo hago solo yo, por esta vez te perdono el error, pero tuve que crear un revert para volver atras lo que hiciste, ahora para volver a crear tus cambios, te recomiendo sacar una nueva rama de main, y reaplicar tus cambios a mano, ya que el revert puede llegar a romper lo que hiciste si tratas de hacer un pull de main.